// The objects the API answers with. Field lists follow the browser's own types in src/app/api/*.ts
// (and the shared ones in src/app/inbox, src/app/broadcasts, src/app/whatsapp), which mirror the server.
import { d, o, t, type Schema } from './helpers.ts'

const ROLE = 'owner|admin|supervisor|agent'
const ts = d('string', 'ISO 8601 time, or milliseconds since 1970 (older rows).')

export const schemas: Record<string, Schema> = {
  Error: o(
    { 'title*': 'string', 'detail*': 'string', status: 'integer' },
    'Every error from our own routes. Relay routes pass Meta’s body through instead: {title, detail} or Graph’s {error: {message, code, fbtrace_id}}.',
  ),

  // ---- Accounts ----
  Me: o({
    'user*': o({ 'id*': 'string', 'name*': 'string', 'email*': 'string' }),
    'workspace*': { anyOf: [o({ 'id*': 'string', 'name*': 'string' }), { type: 'null' }] },
    'role*': t(`${ROLE}?`),
    'setup*': d('complete|account|password', '`account`: email verified, name, password and workspace still to set. `password`: opened a reset link.'),
    'joining*': { anyOf: [o({ workspaceName: 'string', inviterName: 'string?' }), { type: 'null' }], description: 'Invited and still setting up: the workspace they’ll join.' },
  }),
  Members: o({
    'members*': 'Member[]',
    'invites*': d('Invite[]', 'Empty unless you can manage members.'),
    'joining*': d(
      { type: 'array', items: o({ email: 'string', verifiedAt: 'date-time' }) },
      'Invited people who verified their email but haven’t finished setting up. Empty unless you can manage members.',
    ),
  }),
  Member: o({ 'userId*': 'string', 'name*': 'string', 'email*': 'string', 'role*': ROLE, 'joinedAt*': 'date-time' }),
  Invite: o({ 'id*': 'string', 'email*': 'string', 'role*': ROLE, 'invitedAt*': 'date-time', 'expiresAt*': 'date-time' }),

  // ---- Inbox ----
  MessageMedia: o({
    'kind*': 'image|video|audio|document|sticker',
    'mime*': 'string',
    id: d('string', 'Stored file id; download with GET /api/inbox/media/{id}.'),
    filename: 'string',
    size: 'integer',
    caption: 'string',
    'state*': d('pending|ready|failed', '`pending`: still being fetched from WhatsApp. `failed`: WhatsApp no longer has it.'),
  }),
  ChatMessage: o({
    'id*': 'string',
    'phone*': 'string',
    'direction*': 'in|out',
    'author*': 'customer|ai|agent|system',
    authorId: 'string',
    authorName: 'string',
    'kind*': 'text|note|media|interactive|template|event',
    'body*': d('string?', 'null for a customer message Meta reported (from a conversation turn) whose words only arrive by webhook.'),
    'at*': 'date-time',
    status: 'sent|delivered|read|failed',
    tools: d('string[]', 'Tools the AI agent used for this reply.'),
    turnId: d('string', 'Set on agent replies rebuilt from Meta’s conversation turns; the text is then a short preview.'),
    media: 'MessageMedia',
  }),
  ChatSummary: o({
    'phone*': 'string',
    'name*': 'string?',
    username: d('string', 'WhatsApp username, for a customer who hides their number.'),
    'tags*': 'string[]',
    'owner*': d('ai|human', 'Who is answering: the AI agent or the team.'),
    'assigneeId*': 'string?',
    'unread*': 'integer',
    'lastMessageAt*': 'date-time?',
    'windowOpen*': d('boolean', 'Inside WhatsApp’s 24-hour window, so free-form replies are allowed.'),
    'sample*': d('boolean', 'Sample data: stored, never sent to WhatsApp.'),
    snoozedUntil: 'date-time?',
    'preview*': { anyOf: [o({ author: 'customer|ai|agent|system', body: 'string?' }), { type: 'null' }] },
  }),
  ChatDetail: o({
    viewers: d({ type: 'array', items: o({ name: 'string', typing: 'boolean' }) }, 'Teammates with this chat open in the last 20 seconds.'),
    'conversation*': o({
      'phone*': 'string',
      'owner*': 'ai|human',
      'assigneeId*': 'string?',
      'lastInboundAt*': 'date-time?',
      'windowOpen*': 'boolean',
      'sample*': 'boolean',
      snoozedUntil: 'date-time?',
    }),
    reminders: d({ type: 'array', items: o({ id: 'string', note: 'string', dueAt: 'date-time' }) }, 'Your reminders still to come for this chat.'),
    'contact*': {
      anyOf: [o({ phone: 'string', name: 'string', username: 'string', tags: 'string[]', fields: { type: 'object', additionalProperties: { type: 'string' } }, blocked: 'boolean' }), { type: 'null' }],
    },
    'messages*': 'ChatMessage[]',
  }),
  CannedResponse: o({ 'id*': 'string', 'title*': 'string', 'shortcut*': 'string', 'body*': 'string', 'shared*': d('boolean', 'Shared with the whole workspace (else only yours).') }),
  SavedView: o({ 'id*': 'string', 'name*': 'string', 'filter*': 'all|mine|unassigned|ai|snoozed', 'q*': 'string' }),
  SearchHit: o({ 'id*': 'string', 'phone*': 'string', 'name*': 'string?', 'body*': 'string', 'at*': 'date-time', 'kind*': 'text|note|media|interactive|template|event', 'author*': 'customer|ai|agent|system' }),

  // ---- Tickets ----
  Ticket: o({
    'id*': 'string',
    'number*': 'integer',
    'phone*': 'string',
    'name*': 'string?',
    'subject*': 'string',
    'status*': 'open|pending|resolved',
    'priority*': 'urgent|high|normal|low',
    'assigneeId*': 'string?',
    'tags*': 'string[]',
    'source*': d('handoff|takeover|reply|manual', 'What opened it: the AI handed off, a teammate took over, a team reply, or created by hand.'),
    'createdAt*': 'date-time',
    'updatedAt*': 'date-time',
    'firstRespondedAt*': 'date-time?',
    'resolvedAt*': 'date-time?',
    'resolution*': 'string?',
    'csat*': { anyOf: [o({ score: { type: 'integer', enum: [1, 2, 3] }, label: 'string', at: 'date-time' }), { type: 'null' }] },
    'sla*': o({ kind: d('firstResponse|resolve|done', 'Which response target is running.'), at: 'date-time?', breached: 'boolean' }),
    sample: 'boolean',
  }),
  SupportSettings: o({
    'hours*': o({
      timezone: d('string', 'IANA time zone, e.g. Asia/Kolkata.'),
      week: d({ type: 'object', additionalProperties: { anyOf: [o({ open: 'string', close: 'string' }), { type: 'null' }] } }, 'Keys sun…sat; times HH:MM; null = closed.'),
      holidays: d('string[]', 'Dates (YYYY-MM-DD).'),
    }),
    'awayMessage*': 'string',
    'sla*': d({ type: 'object', additionalProperties: o({ firstResponse: 'number', resolve: 'number' }) }, 'Per priority (urgent, high, normal, low): minutes of business time.'),
    'routing*': o({ mode: 'unassigned|round_robin|fixed', teamId: 'string?', userId: 'string?' }),
    'teams*': { type: 'array', items: o({ id: 'string', name: 'string', memberIds: 'string[]' }) },
    'csat*': o({ enabled: 'boolean', question: 'string' }),
    'restrictAgents*': d('boolean', 'Agents see only their own chats and tickets, plus unassigned ones.'),
    aiSummary: d('boolean', 'Read-only: the server can write AI summaries (ANTHROPIC_API_KEY is set).'),
    saved: d('boolean', 'Read-only: false until the workspace saves these settings (the values are then Helo.ai’s defaults).'),
    listenOnly: d('boolean', 'Read-only: the business’s own number, where the console sends nothing on its own (no away message, no feedback question).'),
  }),
  Notice: o(
    {
      'id*': d('string', 'Alerts look like `alert:<key>`, reminders `reminder:<id>`.'),
      'kind*': 'breached|due|assigned|unassigned|alert|alert_critical|reminder',
      'text*': 'string',
      'at*': 'date-time',
      number: d('integer', 'Ticket notices.'),
      phone: d('string', 'Ticket and reminder notices.'),
      target: d('billing|whatsapp|broadcasts', 'Alerts: which page to open.'),
    },
    'A ticket notice, an alert (owners and admins) or one of your reminders.',
  ),
  SupportAnalytics: o({
    'days*': 'integer',
    'timezone*': 'string',
    'series*': { type: 'array', items: o({ date: 'string', created: 'integer', resolved: 'integer' }) },
    'created*': 'integer',
    'resolved*': 'integer',
    'open*': 'integer',
    'medianFirstReplyMin*': 'number?',
    'medianResolveMin*': 'number?',
    'slaFirstReplyMet*': d('number?', 'Share met, 0–1.'),
    'slaResolveMet*': 'number?',
    'csat*': o({ responses: 'integer', average: 'number?', good: 'integer', okay: 'integer', bad: 'integer' }),
    'chats*': o({ total: 'integer', aiOnly: 'integer', withTeam: 'integer' }),
    'people*': { type: 'array', items: o({ name: 'string', resolved: 'integer', open: 'integer', medianFirstReplyMin: 'number?' }) },
    'broadcasts*': o({ sent: 'integer', read: 'integer', replied: 'integer' }),
  }),

  // ---- Contacts ----
  Contact: o({
    'phone*': d('string', 'Phone number, or BSUID for a customer who hides their number.'),
    'name*': 'string?',
    username: 'string',
    'email*': 'string?',
    'tags*': 'string[]',
    'fields*': d({ type: 'object', additionalProperties: { type: 'string' } }, 'Custom field values by field key (see /api/contacts/fields).'),
    optedOut: d('boolean', 'Opted out of broadcasts.'),
    'source*': 'whatsapp|manual|import|sample',
    'createdAt*': 'date-time',
    lastSeenAt: 'date-time',
    openTicket: 'boolean',
  }),
  ContactInput: o({
    phone: d('string', 'Required when creating. 8 to 15 digits, country code first.'),
    name: 'string?',
    email: 'string?',
    tags: d({ anyOf: [t('string[]'), t('string')] }, 'A list, or one comma-separated string.'),
    fields: { type: 'object', additionalProperties: { type: 'string' } },
    optedOut: 'boolean',
  }),
  FieldDef: o({ 'key*': 'string', 'label*': 'string', 'type*': 'text|number|date|select', options: d('string[]', 'For `select`.') }),
  SegmentFilter: o({
    tags: d('string[]', 'Contacts with any of these tags.'),
    field: { anyOf: [o({ key: 'string', value: 'string' }), { type: 'null' }] },
    activeDays: d('integer?', 'Wrote to you in the last N days.'),
    includeOptedOut: 'boolean',
  }),
  Segment: o({ 'id*': 'string', 'name*': 'string', 'filter*': 'SegmentFilter', 'count*': d('integer', 'Contacts that match now.') }),

  // ---- Broadcasts ----
  TemplateComponent: o({
    'type*': 'HEADER|BODY|FOOTER|BUTTONS',
    format: 'TEXT|IMAGE|VIDEO|DOCUMENT|LOCATION',
    text: 'string',
    buttons: { type: 'array', items: o({ type: 'string', text: 'string', url: 'string', phone_number: 'string' }) },
  }),
  WaTemplate: o({
    'id*': 'string',
    'name*': 'string',
    'language*': 'string',
    'status*': d('string', 'Meta’s review status: APPROVED, PENDING, REJECTED…'),
    'category*': 'string',
    rejectedReason: 'string',
    'components*': 'TemplateComponent[]',
  }),
  BroadcastStats: o({
    'queued*': 'integer',
    'sent*': 'integer',
    'delivered*': 'integer',
    'read*': 'integer',
    'failed*': 'integer',
    'skipped*': 'integer',
    'replied*': 'integer',
    'retrying*': d('integer', 'Queued again after a failure WhatsApp asked us to retry (e.g. its daily marketing limit).'),
  }),
  Broadcast: o({
    'id*': 'string',
    'name*': 'string',
    'template*': o({ name: 'string', language: 'string' }),
    'segmentId*': 'string?',
    'segmentName*': 'string',
    'audienceCount*': 'integer',
    'status*': 'scheduled|sending|completed|cancelled',
    'scheduledAt*': 'date-time',
    startedAt: 'date-time',
    completedAt: 'date-time',
    'createdByName*': 'string',
    'createdAt*': 'date-time',
    'stats*': 'BroadcastStats',
  }),
  BroadcastDetail: {
    allOf: [
      { $ref: '#/components/schemas/Broadcast' },
      o({
        'preview*': d('string', 'The message as the first recipient sees it.'),
        'failures*': { type: 'array', items: o({ reason: 'string', retrying: 'boolean', count: 'integer', nextAt: 'date-time?' }) },
        'recipients*': {
          type: 'array',
          items: o({ phone: 'string', name: 'string?', status: 'string', reason: 'string', error: 'string', retryAt: 'date-time', sentAt: 'date-time' }),
        },
      }),
    ],
  },
  Preflight: o({
    'audience*': 'integer',
    'sample*': d('integer', 'Sample contacts: stored, never sent to WhatsApp.'),
    'hiddenNumbers*': d('integer', 'Customers who hide their number.'),
    'gotMarketingToday*': d('integer', 'Already got a marketing message from you in the last 24 hours.'),
    'estimate*': o({
      currency: 'string?',
      total: 'number',
      unpriced: d('integer', 'People whose country has no recent rate, so they aren’t in `total`.'),
      countries: { type: 'array', items: o({ country: 'string', people: 'integer', rate: 'number?' }) },
    }),
  }),

  // ---- Agent store ----
  StoredAgent: o({
    'phoneNumberId*': 'string',
    wabaId: 'string',
    displayName: 'string',
    createdAt: ts,
    everLive: d('boolean', 'Has ever answered customers (Publish).'),
    lastOpenedAt: ts,
    onboardedAt: ts,
  }),
  StoredTrace: o({
    'conversationId*': 'string',
    'consumer*': d('string', 'Customer phone (or test id).'),
    'startedAt*': ts,
    'endedAt*': ts,
    'turns*': {
      type: 'array',
      items: o({
        turnId: 'string',
        ts,
        e2eLatencyMs: 'integer?',
        steps: { type: 'array', items: o({ type: 'LLM_CALL|TOOL_CALL', status: 'SUCCESS|ERROR|TIMEOUT', tool_name: 'string', latency_ms: 'integer' }) },
      }),
    },
  }),
  AuditRow: o({
    'at*': ts,
    'action*': 'create|update|delete|test|run',
    'resource*': d('string', 'Which part of the agent, e.g. faq, skills, agent-ui-skills.'),
    'resourceId*': 'string?',
    'status*': d({ anyOf: [t('integer'), t('string')] }, 'Meta’s HTTP status.'),
    'summary*': { type: 'object', additionalProperties: { anyOf: [t('string'), t('number'), t('boolean')] } },
  }),

  // ---- Billing, numbers, WhatsApp ----
  Billing: o({
    'currency*': 'string?',
    'budget*': d('number?', 'Monthly spending alert threshold.'),
    'lastSyncAt*': 'date-time?',
    'lastSyncError*': 'string?',
    'month*': o({ total: 'number', byCategory: { type: 'array', items: o({ category: 'string', cost: 'number', volume: 'integer' }) } }),
    'days*': { type: 'array', items: o({ day: 'string', cost: 'number', volume: 'integer' }) },
    'ai*': o({
      console: { type: 'array', items: o({ feature: 'string', model: 'string', input: 'integer', output: 'integer', calls: 'integer' }) },
      agentConversations: 'integer?',
      agentUsage: d(
        o({ state: d('string?', 'ok, no_billable_account (Meta reports usage once the agent has a payment method), error_<status>, or null before the first check.'), checkedAt: 'date-time?', billableMessages: 'integer', billableTokens: 'integer', cost: 'number' }),
        'Meta Business Agent usage this month (business_agent_insights, collected hourly).',
      ),
    }),
    messages: d(
      o({ billable: 'integer', free: 'integer', byCategory: { type: 'array', items: o({ category: 'string', billable: 'integer', free: 'integer' }) } }),
      'This month’s messages as WhatsApp priced them in their status webhooks.',
    ),
  }),
  WaNumber: o({
    'id*': 'string',
    'wabaId*': 'string',
    'wabaName*': 'string',
    'display*': d('string', 'The number as people dial it.'),
    'verifiedName*': 'string',
    'status*': 'string',
    'codeVerification*': 'string?',
    'quality*': d('string', 'GREEN, YELLOW, RED or UNKNOWN.'),
    'nameStatus*': 'string?',
    'newName*': 'string?',
    'newNameStatus*': 'string?',
    'platform*': 'string?',
    sandbox: d('boolean', 'A Meta test number (sandbox): replies reach only up to 5 verified recipients.'),
    'throughput*': 'string?',
    'photo*': 'string?',
    'limit*': d('string?', 'Messaging limit tier.'),
    'pinKnown*': 'boolean',
    'syncedAt*': 'date-time',
  }),
  Profile: o({ 'about*': 'string', 'address*': 'string', 'description*': 'string', 'email*': 'string', 'websites*': 'string[]', 'vertical*': 'string' }),
  Automation: o({ 'prompts*': d('string[]', 'Ice breakers.'), 'commands*': { type: 'array', items: o({ name: 'string', description: 'string' }) } }),
  NumberDetail: o({
    'number*': 'WaNumber',
    'profile*': { allOf: [{ $ref: '#/components/schemas/Profile' }, o({ photo: 'string?' })] },
    'automation*': 'Automation',
    'official*': d('boolean?', 'Official business account (green tick).'),
    'pinStorage*': d('boolean', 'The server can store this number’s PIN (TOKEN_ENCRYPTION_KEY is set).'),
    managed: d('boolean', 'The business’s own number: registration, PIN and codes can’t be changed here.'),
    'activity*': { type: 'array', items: o({ kind: 'string', data: 'object', at: 'date-time', by: 'string' }) },
  }),
  WaAccount: o({
    'wabaId*': 'string',
    'wabaName*': 'string',
    'businessId*': 'string',
    'phoneNumbers*': { type: 'array', items: o({ id: 'string', display: 'string', verifiedName: 'string', sandbox: d('boolean', 'A Meta test number: it can only message up to 5 verified recipients.') }) },
    'source*': d('env|signup|coexistence', '`env`: the server’s own number from .env.'),
    'billing*': o({ mode: 'partner_credit|own', state: 'shared|pending|confirmed|failed', error: 'string' }),
    'steps*': d(
      { type: 'object', additionalProperties: o({ state: 'done|failed|skipped', at: 'date-time', error: 'string' }) },
      'Signup steps (exchange, subscribe, register, billing, sync, details) and how each went.',
    ),
    'hasPin*': 'boolean',
    'canDisconnect*': 'boolean',
    'needsAttention*': 'boolean',
    protected: d('boolean', 'The business’s own account: read and agent configuration only; its webhooks, registration, PIN and billing are never changed here.'),
    'createdAt*': 'date-time',
  }),
  NumberHealth: o({
    'phoneNumberId*': 'string',
    'display*': 'string',
    'name*': 'string?',
    'quality*': 'string',
    'nameStatus*': 'string?',
    'status*': 'string?',
    'limit*': 'string?',
    'limitLabel*': 'string?',
    'checkedAt*': 'date-time',
  }),
  Gap: o({
    'question*': 'string',
    'reason*': d('fallback|handoff', 'The agent answered with Meta’s fallback, or handed the chat to a person.'),
    'source*': 'customer|test',
    'count*': d('integer', 'How many times it was asked.'),
    'lastAt*': 'date-time',
  }),
}
